version: '3.7'
services:
  web_react:
    stdin_open: true  
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: npm run --prefix frontend start  
  web_api:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db_api 
  db_api:
    restart: always 
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
volumes:
  postgres_data:
